echo "==================================================="
echo "The env values"
echo "CYPRESS_BASE_URL=$CYPRESS_BASE_URL"
echo "CYPRESS_UI_LINK=$CYPRESS_UI_LINK"
echo "CYPRESS_USERNAME=$CYPRESS_USERNAME"
echo "CYPRESS_LOGIN_FLOW=$CYPRESS_LOGIN_FLOW"
echo "CYPRESS_LOGIN_DOMAIN=$CYPRESS_LOGIN_DOMAIN"
echo "CYPRESS_COMPARTMENT_NAME=$CYPRESS_COMPARTMENT_NAME"
echo "CYPRESS_BUCKET_NAME=$CYPRESS_BUCKET_NAME"
echo "CYPRESS_FOLDER_NAME=$CYPRESS_FOLDER_NAME"
echo "CYPRESS_EXCLUDE_SPEC_PATTERN=$CYPRESS_EXCLUDE_SPEC_PATTERN"

npm run cypress-install --prefix /usr/src/app/

npm start --prefix /usr/src/app/